Реализация тестового задания
aspnetman/OptimalPacking pull request #1
Opened 2024-12-16 13:14 UTC by aspnetman

2024-12-16 15:24 UTC, vbnz34343434 requested changes
В целом неплохая работа с самого начала. 
Неплохо декомпозирован код.

2024-12-16 15:24 UTC, vbnz34343434 commented on logs/2024-12-16.log
> +2024-12-16 16:09:14.060 [main] INFO  r.l.p.importPackages.entities.Truck - Текущий вид кузова:
папка с логами должна быть в .gitignore

2024-12-16 15:24 UTC, vbnz34343434 commented on src/main/java/ru/liga/App.java
> +    private static void start() throws Exception {
в целом было необязательно выносить это в отдельный метод, но вообще основной класс приложения чистенький, мне нравится

2024-12-16 15:24 UTC, vbnz34343434 commented on src/main/java/ru/liga/App.java
> +package ru.liga;
по-хорошему, здесь должен быть еще один пакет с самим названием проекта и App и дочерние должны быть уже в нем

2024-12-16 15:24 UTC, vbnz34343434 commented on src/main/java/ru/liga/App.java
> +    private static final Logger logger = LoggerFactory.getLogger(App.class);
круто, что сразу воспользовался логгером

2024-12-16 15:24 UTC, vbnz34343434 commented on pom.xml
> +        <dependency>
обращай внимание на подсветку в идее - в неактуальных версиях зависимостей могут быть уязвимости. В реальных проектах какие-нить безы могут просить обновиться до версий без уязвимости

2024-12-16 15:24 UTC, vbnz34343434 commented on logs/2024-12-16.log
> +2024-12-16 16:09:14.071 [main] INFO  r.l.p.importPackages.entities.Truck - XXX...XXX...XXX...XXX...............
а что с алгоритмом, я не совсем понимаю? почему такой странный вывод? 

плюс, я бы очень хотел отличать посылки друг от друга

2024-12-16 15:24 UTC, vbnz34343434 commented on src/main/java/ru/liga/controller/ConsoleController.java
> +            var response = this.importPackagesCommandHandler.handle(new ImportPackagesCommand(command));
`this.` не обязательно указывать

2024-12-16 15:24 UTC, vbnz34343434 commented on src/main/java/ru/liga/packages/importPackages/ImportPackagesCommandHandler.java
> +    public int packParcels(List<Parcel> parcels) {
метод публичный, а используется только этим классом, не надо так

2024-12-16 15:24 UTC, vbnz34343434 commented on src/main/java/ru/liga/packages/importPackages/entities/Truck.java
> +            log.info(gird);
вот такие вещи в цикле на уровне info обычно не логируют, для этого понижают такие вещи до дебага.

2024-12-16 15:24 UTC, vbnz34343434 commented on logs/2024-12-16.log
> +2024-12-16 16:12:58.865 [main] INFO  r.liga.controller.ConsoleController - Необходимое количество машин: 6
по сути все что выше, я так понимаю это промежуточные какие-то варианты. В задании указано не кол-во машин вывести, а уже упакованные посылки (финальный вариант)

2024-12-16 15:24 UTC, vbnz34343434 commented on src/main/resources/packages.txt
> +5,1
на вход тоже не такой файл идет

2024-12-16 15:24 UTC, vbnz34343434 commented on src/main/java/ru/liga/packages/importPackages/FileParcer.java
> +    public static List<Parcel> readParcelsFromFile(String fileName) throws Exception {
от checked-исключений следует избавляться и перехватывать их в местах где они выбрасываются, преобразуя их в unchecked. А то этот `throws` у тя тянется до самого App, через 4 класса

2024-12-16 15:24 UTC, vbnz34343434 commented on src/main/java/ru/liga/packages/importPackages/ImportPackagesCommand.java
> +    public ImportPackagesCommand(String pathToFile) {
если уж используешь lombok, то используй его по-полной. Конструктор может сгенериться им например

2024-12-16 15:24 UTC, vbnz34343434 commented on src/main/java/ru/liga/packages/importPackages/entities/Parcel.java
> +    int height;
! ВСЕ поля должны быть приватными и доступ к полям должен быть только через геттеры и сеттеры

2024-12-16 15:24 UTC, vbnz34343434 commented on src/main/java/ru/liga/packages/importPackages/entities/Truck.java
> +@Setter
кажется для этого класса не нужны ни геттеры, ни сеттеры, внутренности класса никем больше не используются

2024-12-16 15:24 UTC, vbnz34343434 commented on src/main/java/ru/liga/controller/ConsoleController.java
> +        while (scanner.hasNextLine()) {
было бы классно, если бы исключения, выбрасываемые приложением, не останавливали бы его работу

2024-12-16 15:30 UTC, vbnz34343434 requested changes

2024-12-16 15:30 UTC, vbnz34343434 commented on src/test/java/ru/liga/packagesTests/PackagesTests.java
> +public class PackagesTests {
Название тест-класса должно соответствовать названию тестируемого класса с постфиксом `Test`. Самый простой способ добавиться этого - на тестируемом классе нажать `Ctrl+Shift+T`

2024-12-17 14:17 UTC, aspnetman commented on logs/2024-12-16.log
> +2024-12-16 16:09:14.060 [main] INFO  r.l.p.importPackages.entities.Truck - Текущий вид кузова:
Добавил в игнор, удалил из VCS

2024-12-17 14:18 UTC, aspnetman commented on src/main/java/ru/liga/App.java
> +    private static void start() throws Exception {
Оставлю как есть

2024-12-17 14:25 UTC, aspnetman commented on src/main/java/ru/liga/App.java
> +package ru.liga;
Переформатировал

2024-12-17 14:27 UTC, aspnetman commented on pom.xml
> +        <dependency>
За основу брал код из консольного приложения, которое давались вашей организацией на лабораторной. После обновления библиотек код не работает, см скрин ниже, пока не стал обновлять.

![image](https://github.com/user-attachments/assets/bfcc3a48-61fd-47c5-b12e-013363f849dc)

2024-12-17 14:29 UTC, aspnetman commented on src/main/java/ru/liga/packages/importPackages/ImportPackagesCommandHandler.java
> +    public int packParcels(List<Parcel> parcels) {
Используется в тестах. Слишком много надо переделывать, чтобы сделать его приватным

2024-12-17 14:35 UTC, aspnetman commented on logs/2024-12-16.log
> +2024-12-16 16:09:14.071 [main] INFO  r.l.p.importPackages.entities.Truck - XXX...XXX...XXX...XXX...............
Пустые клетки представлены символом ., а заполненные — символом X
Оставляю без изменений, нет времени на эту правку

2024-12-17 14:37 UTC, aspnetman commented on src/main/java/ru/liga/controller/ConsoleController.java
> +            var response = this.importPackagesCommandHandler.handle(new ImportPackagesCommand(command));
Таким образом понятно к кому я обращаюсь к полю класса или к локальной переменной, что важно при чтении кода. У нас в компании используем this. Оставлю без изменений

2024-12-17 14:38 UTC, aspnetman commented on src/main/java/ru/liga/packages/importPackages/entities/Truck.java
> +            log.info(gird);
Исправил

2024-12-17 14:41 UTC, aspnetman commented on src/main/resources/packages.txt
> +5,1
На вход указывается ширина и высота и у грузовика есть ширина и высота, что логично. Файл который указан в задаче неверный по своей сути

2024-12-17 14:47 UTC, aspnetman commented on src/main/java/ru/liga/packages/importPackages/FileParcer.java
> +    public static List<Parcel> readParcelsFromFile(String fileName) throws Exception {
Убрал

2024-12-17 14:47 UTC, aspnetman commented on src/main/java/ru/liga/packages/importPackages/FileParcer.java
> +    public static List<Parcel> readParcelsFromFile(String fileName) throws Exception {
Убрал

2024-12-17 15:06 UTC, aspnetman commented on src/test/java/ru/liga/packagesTests/PackagesTests.java
> +public class PackagesTests {
Переименовал

2024-12-17 15:09 UTC, aspnetman commented on src/main/java/ru/liga/packages/importPackages/entities/Parcel.java
> +    int height;
Исправил

2024-12-18 08:06 UTC, vbnz34343434 commented on src/main/java/ru/liga/App.java
> +package ru.liga;
Основной класс тоже должен быть внутри этого пакета

2024-12-18 08:25 UTC, vbnz34343434 requested changes

2024-12-18 08:25 UTC, vbnz34343434 commented on src/main/java/ru/liga/optimalpacking/packages/importpackages/ImportPackagesCommand.java
> +    public ImportPackagesCommand(String pathToFile) {
конструктор не нужен, @Data уже предоставляет генерацию его

2024-12-18 08:25 UTC, vbnz34343434 commented on pom.xml
> +        <dependency>
ну лабы не обновляются каждый день, это нормальная история. 
подозреваю что на скрине просто конфликт версий logback-classic и logback-core, вот с такими зависимостями все ок работает 
![image](https://github.com/user-attachments/assets/2b58f59b-94a7-4e94-b2c2-e48736369055)

2024-12-18 08:25 UTC, vbnz34343434 commented on src/main/java/ru/liga/controller/ConsoleController.java
> +            var response = this.importPackagesCommandHandler.handle(new ImportPackagesCommand(command));
возможно в каком-то другом языке - да. 
В Java это необходимо только при пересечении имен (например в конструкторах или любом другом случае наличия переменной с тем же названием что и поля). Во всех остальных случаях это избыточно.

2024-12-18 08:25 UTC, vbnz34343434 commented on src/main/java/ru/liga/packages/importPackages/ImportPackagesCommandHandler.java
> +    public int packParcels(List<Parcel> parcels) {
ну он публичный именно из-за тестов, такого быть не должно. 
Либо тесты написаны некорретно и тестируют не то что нужно, либо декомпозиция недостаточная, если тебе приходится писать тест на приватный (по сути) метод

2024-12-18 08:25 UTC, vbnz34343434 commented on src/main/java/ru/liga/optimalpacking/packages/importpackages/entities/Parcel.java
> +@Setter
@Data уже содержит в себе и геттеры и сеттеры

2024-12-18 08:25 UTC, vbnz34343434 commented on src/main/java/ru/liga/optimalpacking/packages/importpackages/entities/Parcel.java
> +    public Parcel(int width, int height) {
замени конструктор на @AllArgsConstructor ломбока

2024-12-18 08:25 UTC, vbnz34343434 commented on src/test/java/ru/liga/packagesTests/ImportPackagesCommandHandlerTest.java
> +package ru.liga.packagesTests;
пакет тестов тоже должен совпадать с пакетом тестируемого класса

2024-12-18 08:25 UTC, vbnz34343434 commented on src/main/java/ru/liga/optimalpacking/packages/importpackages/FileParcer.java
> +            throw new RuntimeException(e);
По-хорошему, если говорить про реальный проект, тут должен быть какой-то кастомный эксепшн, но т.к. работа тестовая - не заставляю

2024-12-18 16:38 UTC, aspnetman commented on src/main/java/ru/liga/App.java
> +package ru.liga;
Перенёс

2024-12-18 16:44 UTC, aspnetman commented on src/main/java/ru/liga/packages/importPackages/ImportPackagesCommand.java
> +    public ImportPackagesCommand(String pathToFile) {
Сделал record, как и должно по сути быть, так как это Dto

2024-12-18 16:45 UTC, aspnetman commented on src/main/java/ru/liga/packages/importPackages/entities/Truck.java
> +@Setter
Убрал

2024-12-18 16:47 UTC, aspnetman commented on src/main/java/ru/liga/controller/ConsoleController.java
> +        while (scanner.hasNextLine()) {
Готово

2024-12-18 16:47 UTC, aspnetman commented on src/main/java/ru/liga/optimalpacking/packages/importpackages/ImportPackagesCommand.java
> +    public ImportPackagesCommand(String pathToFile) {
Сделал record

2024-12-18 17:03 UTC, aspnetman commented on src/main/java/ru/liga/packages/importPackages/ImportPackagesCommandHandler.java
> +    public int packParcels(List<Parcel> parcels) {
Исправил

2024-12-18 17:04 UTC, aspnetman commented on src/main/java/ru/liga/controller/ConsoleController.java
> +            var response = this.importPackagesCommandHandler.handle(new ImportPackagesCommand(command));
Не согласен. Главное не как там принято, а как тебе удобно и как принято в компании. Исправил.

2024-12-19 13:31 UTC, vbnz34343434 commented
Можешь мерджить, но с оговоркой, что по сути своей задача не решена - вход/выход в программе реализован не по заданию, алгоритм погрузки реализован только один.

2024-12-19 15:32 UTC, aspnetman commented on src/main/java/ru/liga/optimalpacking/packages/importpackages/entities/Parcel.java
> +    public Parcel(int width, int height) {
Заменил в итоге на record

2024-12-19 15:34 UTC, aspnetman commented on src/test/java/ru/liga/packagesTests/ImportPackagesCommandHandlerTest.java
> +package ru.liga.packagesTests;
Поправил

2024-12-19 15:38 UTC, merged