Реализация тестового задания номер 2
aspnetman/OptimalPacking pull request #2
Opened 2024-12-23 08:19 UTC by aspnetman

2024-12-25 08:30 UTC, boris-dev requested changes

2024-12-25 08:30 UTC, boris-dev commented on src/main/java/ru/liga/optimalpacking/App.java
>      private static final Logger logger = LoggerFactory.getLogger(App.class);
Так как в других классах логер иницилизирован ломбоком - нужно сделать единообразно, предлагаю везде ломбок

2024-12-25 08:30 UTC, boris-dev commented on src/main/java/ru/liga/optimalpacking/App.java
> +                                new ru.liga.optimalpacking.packages.importpackages.businessRules.BusinessRulesChecker(new CheckFilledTrucksExceededMaxValueBusinessRule())),
Пишем пакеты только когда есть реальное пересечение по названиям в этом классе

2024-12-25 08:30 UTC, boris-dev commented on src/main/java/ru/liga/optimalpacking/packages/importpackages/TrucksRepository.java
> +    public void saveResultsToJSON(List<Truck> trucks, String filename) {
по конвенции Json

2024-12-25 08:30 UTC, boris-dev commented on src/main/java/ru/liga/optimalpacking/packages/exportpackages/TrucksProvider.java
> +        return Arrays.stream(trucks).toList();
Это хорошо, это иммутабельный лист

2024-12-25 08:30 UTC, boris-dev commented on src/main/java/ru/liga/optimalpacking/controller/ConsoleController.java
> +                else {
Не забывай форматировать код, всегда нажимай Ctrl+Alt+L идея сама отформатирует

2024-12-25 08:30 UTC, boris-dev commented on src/main/java/ru/liga/optimalpacking/controller/ConsoleController.java
> +                else {
Если придет, что угодно идем по этой ветке, нужна конкретика, и если не попали в это условие - выдавать ошибку о неверной команде

2024-12-25 08:30 UTC, boris-dev commented on src/main/java/ru/liga/optimalpacking/controller/ConsoleController.java
> +                    pipeline.send(new ExportPackagesCommand("[{\"parcels\":[{\"width\":3,\"height\":4}],\"empty\":false,\"id\":\"5eadeb00-b1c3-49d3-b66a-4ff2951b5836\"},{\"parcels\":[{\"width\":4,\"h
Данные должны приходить извне, все параметры команды зашиты в неё саму, т.е. не нужно ждать нескольких вводов, пусть сразу приходит что нужно

2024-12-25 08:30 UTC, boris-dev commented on src/main/java/ru/liga/optimalpacking/controller/ConsoleController.java
> +                    pipeline.send(new ImportPackagesCommand(FileParcer.readParcelsFromFile(command), 20, PackingAlgorithm.DensePacking));
FileParcer возвращает доменный объект, поэтому не должен иметь статик метод, его нужно инжектить в контроллер, также внутри него нужно сделать SneakyThrows

2024-12-25 08:30 UTC, boris-dev commented on src/main/java/ru/liga/optimalpacking/packages/exportpackages/ExportPackagesCommandHandler.java
> +        String fileName = "parcels.json";
В константы

2024-12-25 08:30 UTC, boris-dev commented on src/main/java/ru/liga/optimalpacking/packages/exportpackages/ExportPackagesCommandHandler.java
> +// Принимает загруженные машины и отдаёт на выход файл со списком посылок
в джавадок

2024-12-25 08:30 UTC, boris-dev commented on src/main/java/ru/liga/optimalpacking/packages/importpackages/ImportPackagesCommandHandler.java
> +        if (command.packingAlgorithm() == PackingAlgorithm.DensePacking) {
Свитч

2024-12-25 08:30 UTC, boris-dev commented on src/main/java/ru/liga/optimalpacking/packages/shared/exceptions/InvalidOperationException.java
> +    private final String message;
У родителя есть месседж, здесь избыточен

2024-12-25 08:30 UTC, boris-dev commented on src/main/java/ru/liga/optimalpacking/packages/importpackages/businessRules/BusinessRulesChecker.java
> +        if (result.getIsBroken()) {
просто isBroken, так принято для булеан переменных

2024-12-25 08:30 UTC, boris-dev commented on src/main/java/ru/liga/optimalpacking/packages/importpackages/PackingAlgorithms.java
> +    Алгоритм равномерной загрузки
джавадок, /** и идея сама создаст правильный формат

2024-12-25 08:30 UTC, boris-dev commented on src/main/java/ru/liga/optimalpacking/packages/importpackages/PackingAlgorithms.java
> +public class PackingAlgorithms {
Здесь нужен полиморфизм, без статики на методах, и алгоритмов 3 - равномерный, плотный и одна машина одна посылка

2024-12-25 08:30 UTC, boris-dev commented on src/main/java/ru/liga/optimalpacking/packages/importpackages/entities/Truck.java
> +    private final List<Parcel> parcels = new ArrayList<>();
Прянято всю инициализацию объекта переносить в конструктор чтобы не размывать логику

2024-12-25 08:30 UTC, boris-dev commented on src/main/java/ru/liga/optimalpacking/packages/importpackages/entities/Truck.java
> +    private final String Id = UUID.randomUUID().toString();
С маленькой буквы

2024-12-25 08:30 UTC, boris-dev commented on src/main/java/ru/liga/optimalpacking/packages/shared/middlewares/ExceptionMiddleware.java
> +            log.error("Error", exception);
Обычно если точно не знаешь что придёт делаем exception.getMessage(). Тогда Информация будет в верхнем эксепшене и не нужно листать вниз. Так чаще всего делаем

2024-12-25 08:30 UTC, boris-dev commented on src/test/java/ru/liga/packages/packingalgorithms/DensePackingTest.java
> +public class DensePackingTest {
Тесты должны относится с классами, которые тестируют один к одному, вижу смысл в том как ты сделал, но это из-за того что у тебя алгоритмы статические методы, нужно сделать под это отдельные классы

2024-12-25 08:30 UTC, boris-dev commented on src/test/java/ru/liga/packages/packingalgorithms/UniformPackingTest.java
> +        assertEquals(2, packingResult.trucks().size());
В тестах прошу всех использовать AssertJ, так как он понятнее и мощнее, чтобы в будущем не миксовать две подхода к ассертам

2024-12-25 08:30 UTC, boris-dev commented on src/main/java/ru/liga/optimalpacking/controller/ConsoleController.java
> +                if (command.equals("export")) {
Команды в константы

2024-12-25 08:35 UTC, aspnetman commented on src/main/java/ru/liga/optimalpacking/controller/ConsoleController.java
> +                else {
Тоже думал об этом но поленился ) поправлю

2024-12-25 15:22 UTC, aspnetman commented on src/main/java/ru/liga/optimalpacking/App.java
>      private static final Logger logger = LoggerFactory.getLogger(App.class);
Исправил

2024-12-25 15:22 UTC, aspnetman commented on src/main/java/ru/liga/optimalpacking/App.java
> +                                new ru.liga.optimalpacking.packages.importpackages.businessRules.BusinessRulesChecker(new CheckFilledTrucksExceededMaxValueBusinessRule())),
Исправил

2024-12-25 15:31 UTC, aspnetman commented on src/main/java/ru/liga/optimalpacking/controller/ConsoleController.java
> +                    pipeline.send(new ExportPackagesCommand("[{\"parcels\":[{\"width\":3,\"height\":4}],\"empty\":false,\"id\":\"5eadeb00-b1c3-49d3-b66a-4ff2951b5836\"},{\"parcels\":[{\"width\":4,\"h
Согласен, но это же тест, обработчик не знает откуда прошли данные, поэтому не буду усложнять, оставлю так

2024-12-25 15:34 UTC, aspnetman commented on src/main/java/ru/liga/optimalpacking/controller/ConsoleController.java
> +                    pipeline.send(new ImportPackagesCommand(FileParcer.readParcelsFromFile(command), 20, PackingAlgorithm.DensePacking));
Исправил

2024-12-25 15:36 UTC, aspnetman commented on src/main/java/ru/liga/optimalpacking/packages/exportpackages/ExportPackagesCommandHandler.java
> +// Принимает загруженные машины и отдаёт на выход файл со списком посылок
Исправлено

2024-12-25 16:00 UTC, aspnetman commented on src/main/java/ru/liga/optimalpacking/packages/shared/exceptions/InvalidOperationException.java
> +    private final String message;
Исправил

2024-12-25 16:01 UTC, aspnetman commented on src/main/java/ru/liga/optimalpacking/packages/importpackages/businessRules/BusinessRulesChecker.java
> +        if (result.getIsBroken()) {
Не совсем понял. Убрать @Getter и сделать public?

![image](https://github.com/user-attachments/assets/603b3f09-3918-43ee-8fec-04432b1e9bd3)

2024-12-25 16:08 UTC, aspnetman commented on src/main/java/ru/liga/optimalpacking/packages/importpackages/entities/Truck.java
> +    private final List<Parcel> parcels = new ArrayList<>();
Исправлено

2024-12-25 16:08 UTC, aspnetman commented on src/main/java/ru/liga/optimalpacking/packages/importpackages/entities/Truck.java
> +    private final String Id = UUID.randomUUID().toString();
Исправлено

2024-12-25 16:08 UTC, aspnetman commented on src/main/java/ru/liga/optimalpacking/packages/shared/middlewares/ExceptionMiddleware.java
> +            log.error("Error", exception);
Исправлено

2024-12-26 13:29 UTC, aspnetman commented on src/main/java/ru/liga/optimalpacking/packages/importpackages/entities/Truck.java
> +    private final String Id = UUID.randomUUID().toString();
Исправил

2024-12-26 13:45 UTC, aspnetman commented on src/main/java/ru/liga/optimalpacking/packages/shared/middlewares/ExceptionMiddleware.java
> +            log.error("Error", exception);
Исправлено

2024-12-26 13:45 UTC, aspnetman commented on src/test/java/ru/liga/packages/packingalgorithms/DensePackingTest.java
> +public class DensePackingTest {
Выделил в отдельные классы

2024-12-26 13:46 UTC, aspnetman commented on src/test/java/ru/liga/packages/packingalgorithms/UniformPackingTest.java
> +        assertEquals(2, packingResult.trucks().size());
Исправил

2024-12-26 13:46 UTC, aspnetman commented on src/main/java/ru/liga/optimalpacking/controller/ConsoleController.java
> +                if (command.equals("export")) {
Исправил

2024-12-27 09:27 UTC, merged