Реализация тестового задания номер 3
aspnetman/OptimalPacking pull request #3
Opened 2024-12-28 16:18 UTC by aspnetman

2025-01-14 13:28 UTC, Raketa30 commented
из глобального:
-круто что юзаешь либу для cli
- структура пакетов под круд-операции избыточная,  для этого достаточно одного  круд сервиса, из за этого непонятны слои приложения, где вообще что находится, из за этого часто используешь полные имена классов 
- тестов несоизмеримо мало

2025-01-14 13:55 UTC, Raketa30 requested changes

2025-01-14 13:55 UTC, Raketa30 commented on pom.xml
> +            <version>1.9.0</version>
версии зависимостей и плагинов вынести в проперти, проект может быть многомодульный и хорошо когда версии находятся в одном месте

2025-01-14 13:55 UTC, Raketa30 commented on src/main/java/ru/liga/optimalpacking/App.java
>  public class App {
этот класс получился какой то многофункциональный, его бы распилить по ответственностям, а то тут и фабрика и процессинг и печатание в консоль, вспоминаем СРП

2025-01-14 13:55 UTC, Raketa30 commented on src/main/java/ru/liga/optimalpacking/App.java
> +    private static final String ExitCommand = "exit";
наименование константы не по конвенции  EXIT_COMMAND

2025-01-14 13:55 UTC, Raketa30 commented on src/main/java/ru/liga/optimalpacking/App.java
> +        FileParser fileParser = new FileParser();
логику чтения из файла вынести в отдельный сервис

2025-01-14 13:55 UTC, Raketa30 commented on src/main/java/ru/liga/optimalpacking/App.java
> +        var sharedParcelsRepository = new ru.liga.optimalpacking.packages.shared.ParcelsRepository(initParcels);
зачем создавать репозиторий и потом к нему какие то фасады? это бессмысленно, удалить лишние и оставить 1

2025-01-14 13:55 UTC, Raketa30 commented on src/main/java/ru/liga/optimalpacking/App.java
> +    private static Options createOptions() {
вынести в отдельную фабрику

2025-01-14 13:55 UTC, Raketa30 commented on src/main/java/ru/liga/optimalpacking/App.java
> +            } catch (Exception ignored) {
ексепшен не глотаем а логгируем

2025-01-14 13:55 UTC, Raketa30 commented on src/main/java/ru/liga/optimalpacking/App.java
> +            } catch (ParseException e) {
ексепшен не глотаем а логгируем

2025-01-14 13:55 UTC, Raketa30 commented on src/main/java/ru/liga/optimalpacking/App.java
> +    private static void processArguments(CommandLine cmd, ConsoleController consoleController) {
вынести в отдельный класс, сделать контроллер зависимостью созданного класса

2025-01-14 13:55 UTC, Raketa30 commented on src/main/java/ru/liga/optimalpacking/controller/ConsoleController.java
>      private static final String ExportCommand = "export";
наименование не по конвенции, + не используемое поле - удалить

2025-01-14 13:55 UTC, Raketa30 commented on src/main/java/ru/liga/optimalpacking/packages/deleteparcel/businessRules/BusinessRulesChecker.java
> +public class BusinessRulesChecker {
максимально абстрактное наименование класса - не пойдет

2025-01-14 13:55 UTC, Raketa30 commented on src/main/java/ru/liga/optimalpacking/packages/deleteparcel/businessRules/BusinessRulesChecker.java
> +package ru.liga.optimalpacking.packages.deleteparcel.businessRules;
наименования пакетов пишутся в нижнем регистре, кемлкейс не пойдет

2025-01-14 13:55 UTC, Raketa30 commented on src/main/java/ru/liga/optimalpacking/packages/deleteparcel/businessRules/CheckParcelExistsBusinessRule.java
> +public class CheckParcelExistsBusinessRule implements BusinessRule<String> {
BusinessRule - наименование интерфейса не отображает то, что это просто валидатор, а не бизнес правило)

2025-01-14 13:55 UTC, Raketa30 commented on src/main/java/ru/liga/optimalpacking/packages/importpackages/FileParser.java
> +        try {
два блока можно объединить

2025-01-14 13:55 UTC, Raketa30 commented on src/main/java/ru/liga/optimalpacking/packages/importpackages/FileParser.java
>              throw new RuntimeException(e);
ошибку заллогировать и желательно дальше кастомный ексепшен пробросить

2025-01-14 13:55 UTC, Raketa30 commented on src/main/java/ru/liga/optimalpacking/packages/importpackages/ImportPackagesCommandHandler.java
> +        var parcels = fileParser.readParcelsFromFile(command.file());
неиспользуемая переменная

2025-01-14 13:55 UTC, Raketa30 commented on src/main/java/ru/liga/optimalpacking/packages/importpackages/ImportPackagesCommandHandler.java
> +    private final FileParser fileParser;
визуальное замечание: в некоторых классах ты не делаешь отступы между зависимостями, а здесь делаешь) делай в едином стиле, что б не было похоже на балабановскую спичечную фабрику)

2025-01-14 13:55 UTC, Raketa30 commented on src/main/java/ru/liga/optimalpacking/packages/importpackages/packingAlgorithms/DensePacking.java
>  package ru.liga.optimalpacking.packages.importpackages.packingAlgorithms;
наименование пакета не по конвенции

2025-01-14 13:55 UTC, Raketa30 commented on src/main/java/ru/liga/optimalpacking/packages/importpackages/FileParser.java
>  public class FileParser {
Название класса абстрактное, у этого класса есть конкретная задача - переименуй класс в соответствии с тем, чем он занимается

2025-01-15 13:36 UTC, aspnetman commented on src/main/java/ru/liga/optimalpacking/App.java
> +        var sharedParcelsRepository = new ru.liga.optimalpacking.packages.shared.ParcelsRepository(initParcels);
Не согласен. 
Вспоминаем принципы архитектуры Vertical Slice: в фиче находится только тот код use-case-а, с которым он работает и ничего более.
На примере фичи Edit на нужно из репозитория две функции: getParcel и editParcel. 
Фича работает со своим репозиторием, нет знания, что внутри там доступ к общему(специфика задачи такая).
Если я фиче дам доступ к общему репозиторию - это будет нарушением принципов архитектуры Vertical Slice

![image](https://github.com/user-attachments/assets/e809a7ad-dfb8-4d57-9baa-009d01a26005)

2025-01-15 13:38 UTC, aspnetman commented on src/main/java/ru/liga/optimalpacking/packages/deleteparcel/businessRules/BusinessRulesChecker.java
> +public class BusinessRulesChecker {
Не согласен. 
Этот класс занимается проверкой бизнес-правил.
Критикуешь - предлагай.

2025-01-15 13:39 UTC, aspnetman commented on src/main/java/ru/liga/optimalpacking/packages/deleteparcel/businessRules/CheckParcelExistsBusinessRule.java
> +public class CheckParcelExistsBusinessRule implements BusinessRule<String> {
Это не валидатор, а именно интерфейс бизнес-правила.
Прошу не путать валидацию и бизнес-правила.

2025-01-15 13:40 UTC, aspnetman commented on src/main/java/ru/liga/optimalpacking/packages/importpackages/FileParser.java
>              throw new RuntimeException(e);
Ничего не надо тут логировать. Прошу вспомнить что такое Cross Cutting Concern и после этого посмотреть реализацию ExceptionMiddleware

2025-01-15 13:41 UTC, aspnetman commented on src/main/java/ru/liga/optimalpacking/packages/importpackages/ImportPackagesCommandHandler.java
> +        var parcels = fileParser.readParcelsFromFile(command.file());
Исправил

2025-01-15 13:44 UTC, aspnetman commented on src/main/java/ru/liga/optimalpacking/App.java
> +            } catch (Exception ignored) {
Поправил

2025-01-15 14:28 UTC, Raketa30 commented on src/main/java/ru/liga/optimalpacking/packages/deleteparcel/businessRules/CheckParcelExistsBusinessRule.java
> +public class CheckParcelExistsBusinessRule implements BusinessRule<String> {
но как не путать, если метод буквально возвращает результат **ВАЛИДАЦИИ** бизнес-правила, и метод называется validate() -> делаю вывод что кривое наименование интерфейса

2025-01-15 14:40 UTC, Raketa30 commented on src/main/java/ru/liga/optimalpacking/packages/importpackages/FileParser.java
>              throw new RuntimeException(e);
ок согласен, но блок надо объединить и можно пробрасывать UncheckedIOException вместо RuntimeException

2025-01-15 14:49 UTC, Raketa30 commented on src/main/java/ru/liga/optimalpacking/packages/deleteparcel/businessRules/BusinessRulesChecker.java
> +public class BusinessRulesChecker {
к примеру ParcelExistsBusinessRuleChecker , BusinessRulesChecker а это название контракта подходит, с методом check

просто банально, если мы к примеру в команде работаем, надо оно мне из десятка BusinessRulesChecker искать нужный? легко ошибиться

2025-01-15 14:59 UTC, Raketa30 commented on src/main/java/ru/liga/optimalpacking/App.java
> +        var sharedParcelsRepository = new ru.liga.optimalpacking.packages.shared.ParcelsRepository(initParcels);
я не спорю, ты отдаешь своему сервису только нужные методы, но какой в этом толк, если условно твой базовый репозиторий публичный, его можно использовать где угодно и когда угодно, расставь тогда правильные модификаторы для классов и методов, что бы  каждый репозиторий можно было использовать  только в своих пакетах

ps: и принципы архитектуры типа solid, kiss, dry и прочее, это не свод жестких правил и указаний

2025-01-15 18:16 UTC, aspnetman commented
> из глобального: -круто что юзаешь либу для cli
> 
> * структура пакетов под круд-операции избыточная,  для этого достаточно одного  круд сервиса, из за этого непонятны слои приложения, где вообще что находится, из за этого часто используешь полные имена классов
> * тестов несоизмеримо мало

Касательно архитектуры - это Vertical Slice, реализация каждой операции инкапсулирована.
Тестов мало - согласен, но пока не решил проблему с алгоритмом, из-за этого

2025-01-15 18:17 UTC, aspnetman commented on src/main/java/ru/liga/optimalpacking/App.java
>  public class App {
Тоже думал об этом. Пока не было телеграма, сейчас всё исправлено с добавлением поддержки телеграма

2025-01-15 18:17 UTC, aspnetman commented on src/main/java/ru/liga/optimalpacking/App.java
> +    private static final String ExitCommand = "exit";
Исправлено

2025-01-15 18:18 UTC, aspnetman commented on src/main/java/ru/liga/optimalpacking/App.java
> +        FileParser fileParser = new FileParser();
Не согласен. Чтение из файла тут нужно для инициализации глобального репозитория - это специфика проекта. Поэтому лучше пусть будет чтение из файла рядом с DI

2025-01-15 18:25 UTC, aspnetman commented on src/main/java/ru/liga/optimalpacking/App.java
> +        var sharedParcelsRepository = new ru.liga.optimalpacking.packages.shared.ParcelsRepository(initParcels);
Базовый репозиторий публичный - это специфика проекта, так не должно быть, считай, что на месте базового репозитория SQL обращение к базе данных. Но поскольку БД у нас нет и мы работаем с данными в памяти, то пока так

2025-01-15 18:25 UTC, aspnetman commented on src/main/java/ru/liga/optimalpacking/App.java
> +    private static Options createOptions() {
Готово

2025-01-15 18:25 UTC, aspnetman commented on src/main/java/ru/liga/optimalpacking/App.java
> +            } catch (ParseException e) {
Готово

2025-01-15 18:25 UTC, aspnetman commented on src/main/java/ru/liga/optimalpacking/App.java
> +    private static void processArguments(CommandLine cmd, ConsoleController consoleController) {
Готово

2025-01-15 18:25 UTC, aspnetman commented on src/main/java/ru/liga/optimalpacking/controller/ConsoleController.java
>      private static final String ExportCommand = "export";
Готово

2025-01-15 18:28 UTC, aspnetman commented on src/main/java/ru/liga/optimalpacking/packages/deleteparcel/businessRules/BusinessRulesChecker.java
> +public class BusinessRulesChecker {
BusinessRulesChecker - это фасад, там внутри может быть много проверок разных бизнес-правил, те один публичный метод и много приватных. Что мне при добавлении каждого бизнес-правила переименовывать?

Например ParcelExistsBusinessAndParcelFoundAnd(....ещё 20 правил)RuleChecker  ))

2025-01-15 18:30 UTC, aspnetman commented on src/main/java/ru/liga/optimalpacking/packages/deleteparcel/businessRules/BusinessRulesChecker.java
> +package ru.liga.optimalpacking.packages.deleteparcel.businessRules;
Переименовал

2025-01-15 18:31 UTC, aspnetman commented on src/main/java/ru/liga/optimalpacking/packages/deleteparcel/businessRules/CheckParcelExistsBusinessRule.java
> +public class CheckParcelExistsBusinessRule implements BusinessRule<String> {
validate имеется в виду validate business rule

2025-01-15 18:34 UTC, aspnetman commented on src/main/java/ru/liga/optimalpacking/packages/importpackages/FileParser.java
> +        try {
Чёт не получилось, студия сама так предложила

2025-01-15 18:40 UTC, aspnetman commented on src/main/java/ru/liga/optimalpacking/packages/importpackages/FileParser.java
>              throw new RuntimeException(e);
Согласен. Сделал

2025-01-15 18:41 UTC, aspnetman commented on src/main/java/ru/liga/optimalpacking/packages/importpackages/ImportPackagesCommandHandler.java
> +    private final FileParser fileParser;
Согласен, проблежался, поправил

2025-01-15 18:42 UTC, Raketa30 commented on src/main/java/ru/liga/optimalpacking/packages/deleteparcel/businessRules/BusinessRulesChecker.java
> +public class BusinessRulesChecker {
привязывай название к юз-кейсу, тебе ж потом самому будет удобно ориентироваться DeleteParcelBusinessRuleChecker, я понимаю что  можно ориентироваться по пакету или полному наименованию класса, но это ж непрактично, ладно сам пишешь-знаешь, а другой разраб придет, будет раздупляться

2025-01-15 18:43 UTC, aspnetman commented on src/main/java/ru/liga/optimalpacking/packages/importpackages/packingAlgorithms/DensePacking.java
>  package ru.liga.optimalpacking.packages.importpackages.packingAlgorithms;
Исправил

2025-01-15 18:44 UTC, aspnetman commented on src/main/java/ru/liga/optimalpacking/packages/importpackages/FileParser.java
>  public class FileParser {
Согласен. Поправил

2025-01-16 07:47 UTC, Raketa30 commented on src/main/java/ru/liga/optimalpacking/App.java
> +        var sharedParcelsRepository = new ru.liga.optimalpacking.packages.shared.ParcelsRepository(initParcels);
я почитал про  Vertical Slice, посмотрел примеры, и все равно уверен что можно просто использовать расшареный репозиторий 😅но ок, мне не принципиально, только переименуй свои репозитории обертки согласно тому чем они занимаются, что бы не вводить никого в заблуждение

EditParcelRepository и тд, хотя это больше похоже на сервис EditParcelService

2025-01-16 07:51 UTC, Raketa30 commented on src/main/java/ru/liga/optimalpacking/App.java
> +                "7589989172:AAFzKmwuDHribOZ0V-uhwxNusIpSRmil5LA", // Перенести в конфиг файл
можно в енвы и доставать их через System.getenv("ENV")

2025-01-16 15:58 UTC, aspnetman commented on src/main/java/ru/liga/optimalpacking/App.java
> +        var sharedParcelsRepository = new ru.liga.optimalpacking.packages.shared.ParcelsRepository(initParcels);
Исправил

2025-01-17 06:52 UTC, Raketa30 commented on src/main/java/ru/liga/optimalpacking/packages/deleteparcel/DeleteParcelsRepository.java
> +    private final ru.liga.optimalpacking.packages.shared.ParcelsRepository parcelsRepository;
можно сократить

2025-01-17 06:53 UTC, Raketa30 commented on src/main/java/ru/liga/optimalpacking/packages/editparcel/EditParcelsRepository.java
> +    private final ru.liga.optimalpacking.packages.shared.ParcelsRepository parcelsRepository;
можно тоже сократить

2025-01-17 08:20 UTC, Raketa30 requested changes

2025-01-17 08:20 UTC, Raketa30 commented on src/main/java/ru/liga/optimalpacking/packages/getparcels/GetParcelsRepository.java
> +    private final ru.liga.optimalpacking.packages.shared.ParcelsRepository parcelsRepository;
еще

2025-01-17 08:20 UTC, Raketa30 commented on src/main/java/ru/liga/optimalpacking/packages/deleteparcel/businessrules/BusinessRulesChecker.java
> +public class BusinessRulesChecker {
BusinessRulesChecker-ы, переименуй, пожалуйста, так же как и репозитории - согласно их юзкейсу

2025-01-17 08:20 UTC, Raketa30 commented on build.gradle
> +    compileOnly("org.projectlombok:lombok:1.18.36")
версии вынести в проперти или в ext {} блок

2025-01-17 09:52 UTC, aspnetman commented on src/main/java/ru/liga/optimalpacking/packages/deleteparcel/DeleteParcelsRepository.java
> +    private final ru.liga.optimalpacking.packages.shared.ParcelsRepository parcelsRepository;
Исправлено

2025-01-17 09:52 UTC, aspnetman commented on src/main/java/ru/liga/optimalpacking/packages/editparcel/EditParcelsRepository.java
> +    private final ru.liga.optimalpacking.packages.shared.ParcelsRepository parcelsRepository;
Исправлено

2025-01-17 09:53 UTC, aspnetman commented on src/main/java/ru/liga/optimalpacking/packages/getparcels/GetParcelsRepository.java
> +    private final ru.liga.optimalpacking.packages.shared.ParcelsRepository parcelsRepository;
Исправлено

2025-01-17 09:55 UTC, aspnetman commented on src/main/java/ru/liga/optimalpacking/packages/deleteparcel/businessrules/BusinessRulesChecker.java
> +public class BusinessRulesChecker {
Исправлено

2025-01-17 10:24 UTC, aspnetman commented on build.gradle
> +    compileOnly("org.projectlombok:lombok:1.18.36")
Добавлен объект Versions

2025-01-17 10:29 UTC, aspnetman commented on src/main/java/ru/liga/optimalpacking/packages/deleteparcel/businessRules/BusinessRulesChecker.java
> +public class BusinessRulesChecker {
Исправил. Но в целом не согласен с замечание. Так как логика юз кейса инкапсулирована, то понятно что BusinessRulesChecker - это проверка правил именно этого кейса

2025-01-17 10:39 UTC, aspnetman commented on pom.xml
> +            <version>1.9.0</version>
Сделал

2025-01-17 11:13 UTC, Raketa30 commented on src/main/java/ru/liga/optimalpacking/App.java
> +                                                new ru.liga.optimalpacking.packages.editparcel.businessrules.CheckParcelExistsBusinessRule(editParcelsRepository)),
еще это можно поправить, и кроме тестов у меня вопросов нет) э

2025-01-17 11:18 UTC, merged